version: "3.8"
services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentnet
    restart: always  

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"  # <--- Change from "fluentbit" to "localhost"
        tag: "app"
    networks:
      - fluentnet

networks:
  fluentnet:
    driver: bridge
