services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    user: root
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentnet
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - fluentbit_logs:/var/log/fluentbit
      - /var/lib/docker/containers:/var/lib/docker/containers:ro  # Ensure access to logs

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit:24224"  # Use service name instead of localhost
        tag: "app"
    networks:
      - fluentnet  # Connect to the same network

networks:
  fluentnet:
    driver: bridge

volumes:
  fluentbit_logs:
