version: "3.8"
services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentnet
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - fluentbit_logs:/var/log/fluentbit
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2020/api/v1/health"]  # Health check
      interval: 5s
      timeout: 2s
      retries: 10

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      fluentbit:
        condition: service_healthy  # Wait for Fluent Bit to be healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit:24224"
        tag: "app"
    networks:
      - fluentnet

networks:
  fluentnet:
    driver: bridge

volumes:
  fluentbit_logs: