version: "3.8"
services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    network_mode: host  # <-- Set host network mode
    restart: always  

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"  # <-- Use localhost when in host network mode
        tag: "app"
    network_mode: host  # <-- Set host network mode

networks:
  fluentnet:
    driver: bridge  # No need for networks section if using host mode
