services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    user: root
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentnet
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./parsers.conf:/fluent-bit/etc/parsers.conf
      - fluentbit_logs:/var/log/fluentbit

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"  # Use localhost instead of fluentbit
        tag: "app"
    network_mode: "service:fluentbit"  # Share the network stack with fluentbit

networks:
  fluentnet:
    driver: bridge

volumes:
  fluentbit_logs: