version: "3.8"
services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentnet
    restart: always
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf  # Mount a custom config file
      - fluentbit_logs:/var/log/fluentbit  # Persistent log storage

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit:24224"  # <--- Use service name instead of localhost
        tag: "app"
    networks:
      - fluentnet

networks:
  fluentnet:
    driver: bridge

volumes:
  fluentbit_logs:  # Define the named volume