version: "3.8"
services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - fluentnet  # <-- Use bridge network for fluentbit
    restart: always  

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit:24224"  # <-- Use fluentbit as the service name here
        tag: "app"
    networks:
      - fluentnet  # <-- Use bridge network for app

networks:
  fluentnet:
    driver: bridge
