version: "3.8"

services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    environment:
      - HOSTNAME=fluentbit
    networks:
      fluentnet:
        aliases:
          - fluentbit  # Ensures this hostname is always available
    restart: always

  app:
    image: alpine
    command: [/bin/echo, "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "fluentbit:24224"  # Fluent Bit hostname inside network
        tag: "app"
    networks:
      - fluentnet

networks:
  fluentnet:
    driver: bridge
