version: "3.8"
services:
  fluentbit:
    image: fluent/fluent-bit:1.7
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    network_mode: host  # <-- Use host network mode for fluentbit
    restart: always  

  app:
    image: alpine
    command: ["/bin/echo", "Listen my log!"]
    depends_on:
      - fluentbit
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"  # <-- Use localhost to avoid IPv6 binding
        tag: "app"
    network_mode: host  # <-- Use host network mode for app

networks:
  fluentnet:
    driver: bridge  # <-- Remove this as we are using host mode
